### ISSUE TITLE
不知为何抓这个博客出错了

### ISSUE THREAD

**Issue by ryuzheng** [knarfeh/SinaBlog2e-book#1]
抓得是这个博客：http://blog.sina.com.cn/u/1180557177

```
Traceback (most recent call last):
  File "SinaBlog2e-book.py", line 11, in <module>
    sina_crawler.start()
  File "/home/ubuntu/workspace/SinaBlog2e-book-master/src/main.py", line 44, in start
    self.create_book(line, counter)
  File "/home/ubuntu/workspace/SinaBlog2e-book-master/src/main.py", line 58, in create_book
    worker_factory(task_package.work_list)  # 执行抓取程序
  File "/home/ubuntu/workspace/SinaBlog2e-book-master/src/worker.py", line 276, in worker_factory
    worker.start()
  File "/home/ubuntu/workspace/SinaBlog2e-book-master/src/worker.py", line 79, in start
    self.start_create_work_list()
  File "/home/ubuntu/workspace/SinaBlog2e-book-master/src/worker.py", line 105, in start_create_work_list
    Control.control_center(argv, self.task_set)
  File "/home/ubuntu/workspace/SinaBlog2e-book-master/src/tools/controler.py", line 19, in control_center
    Control.thread_pool.map(**argv)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
IndexError: list index out of range
```

抓另一个新浪博客没报错，尝试用EE-book，但是可能还没支持，提示：

```
Traceback (most recent call last):
  File "ee-book.py", line 102, in <module>
    game.begin()
  File "/home/ubuntu/workspace/EE-Book-master/src/main.py", line 87, in begin
    file_name = self.create_book(self.url, 1)
  File "/home/ubuntu/workspace/EE-Book-master/src/main.py", line 109, in create_book
    worker_factory(task_package.work_list)  # 执行抓取程序
  File "/home/ubuntu/workspace/EE-Book-master/src/worker/worker_factory.py", line 25, in worker_factory
    worker = type_list[key](task[key])
  File "/home/ubuntu/workspace/EE-Book-master/src/worker/page_worker.py", line 38, in __init__
    Http.set_cookie()
  File "/home/ubuntu/workspace/EE-Book-master/src/tools/http.py", line 116, in set_cookie
    result = DB.cursor.execute("select cookieStr, recordDate from LoginRecord order by recordDate desc")
sqlite3.OperationalError: no such table: LoginRecord
```

**Comment by nujeh** [comment]
感谢反馈，问题已经解决:)
用EE-Book可以生成了：   

![screen_shot_2016-05-15_at_10_07_50](https://cloud.githubusercontent.com/assets/6964284/15271667/0f5de358-1a87-11e6-86af-28d800928195.jpg)

<img width="1078" alt="screen shot 2016-05-15 at 10 08 20" src="https://cloud.githubusercontent.com/assets/6964284/15271648/c1c54826-1a85-11e6-97e9-8ff9103c8cb7.png">

新浪博客的页面结构太乱了点。。。之前的Parser考虑不周，爬取个人简介的代码有点问题，目前已经解决了。这个repo大概不会更新了，最新的代码会放在[EE-Book](http://github.com/knarfeh/EE-Book)上，pull最新的代码就可以运行了，以后有什么问题在EE-Book的repo提Issues吧:sweat_smile:

再次感谢反馈

**Comment by ryuzheng** [comment]
好的，谢谢
