### ISSUE TITLE
执行报错！

### ISSUE THREAD

**Issue by starjason** [knarfeh/SinaBlog2e-book#2]
2016-11-25 09:43:33,591 - worker.py:140 - main - 所有内容抓取完毕，开始对页面进行解析
正在解析第283/283张页面2016-11-25 09:43:40,969 - worker.py:146 - main - 网页内容解析完毕
2016-11-25 09:43:41,173 - main.py:59 - main - 网页信息抓取完毕
2016-11-25 09:43:41,174 - main.py:62 - main - 开始从数据库中生成电子书
2016-11-25 09:46:35,702 - http.py:52 - main - 打开网页超时
2016-11-25 09:46:35,702 - http.py:53 - main - 超时页面:http://s12.sinaimg.cn/middle/59ca100agc6d1d9a6fe9b&amp;690
2016-11-25 09:47:42,509 - http.py:48 - main - 网络连接异常
2016-11-25 09:47:42,509 - http.py:49 - main - 异常页面: http://gnome.ik8.com/qsmd/qs/tp/qs002.gif
2016-11-25 09:47:42,509 - http.py:50 - main - 异常原因:timed out
2016-11-25 09:52:00,257 - http.py:58 - main - 未知错误
2016-11-25 09:52:00,257 - http.py:59 - main - 错误页面:http://s7.sinaimg.cn/mw690/59ca100agx6CfR4qzEGf6&amp;690
2016-11-25 09:52:00,280 - http.py:60 - main - 错误堆栈信息:Traceback (most recent call last):
  File "/home/ubuntu/SinaBlog2e-book/src/tools/http.py", line 41, in get_content
    response = urllib2.urlopen(request, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

**Comment by nujeh** [comment]
能说一下做了什么操作吗，输入的网址是？

**Comment by starjason** [comment]
@knarfeh  执行 SinaBlog2e-book.py 操作
